version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: lmk-mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lmk
    volumes:
      - mongodb_data:/data/db
    networks:
      - lmk-network

  mongo-express:
    image: mongo-express:1.0
    container_name: lmk-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - lmk-network

volumes:
  mongodb_data:

networks:
  lmk-network:
    driver: bridge